# Generated by Django 5.0.6 on 2024-09-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_first_dispatch', models.DateTimeField(blank=True, null=True, verbose_name='Дата первой отправки')),
                ('periodicity', models.CharField(blank=True, choices=[('D', 'Раз в день'), ('W', 'Раз в неделю'), ('M', 'Раз в месяц')], help_text='Выберите периодичность отправки', max_length=1, null=True, verbose_name='Периодичность отправки')),
                ('status', models.CharField(choices=[('C', 'Создана'), ('W', 'Запущена'), ('F', 'Завершена')], max_length=20, verbose_name='Статус рассылки')),
                ('datetime_to_start', models.DateTimeField(blank=True, help_text='Введите дату и время, когда нужно отправить рассылку', null=True, verbose_name='Когда нужно разослать?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания рассылки')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('status',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Рассылка', help_text='Введите заголовок', max_length=100, verbose_name='Заголовок')),
                ('message', models.TextField(help_text='Введите текс', verbose_name='Сообщение')),
                ('image', models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='blog/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Заполните почту для рассылки', max_length=100, verbose_name='Почта для рассылки')),
                ('name', models.CharField(blank=True, help_text='Введите имя клиента', max_length=100, null=True, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, help_text='Добавьте комментарий', null=True, verbose_name='Комментарий')),
                ('mailings', models.ManyToManyField(related_name='Client', to='mailing.mailing')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_first_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Дата первой попытки')),
                ('date_last_attempt', models.DateTimeField(auto_now=True, verbose_name='Дата последней попытки')),
                ('status', models.BooleanField(verbose_name='Статус рассылки')),
                ('server_response', models.CharField(max_length=50, verbose_name='Ответ сервера')),
                ('mailing_id', models.ForeignKey(help_text='Выберите рассылку', on_delete=django.db.models.deletion.CASCADE, related_name='Attempt', to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ('status',),
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message_id',
            field=models.ForeignKey(help_text='Выберите сообщение', on_delete=django.db.models.deletion.CASCADE, related_name='Mailing', to='mailing.message', verbose_name='Сообщение'),
        ),
    ]
