# Generated by Django 5.0.6 on 2024-09-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mailings',
        ),
        migrations.AddField(
            model_name='mailing',
            name='client_list',
            field=models.ManyToManyField(help_text='выберите клиентов для рассылки', related_name='Client', to='mailing.client', verbose_name='Клиенты'),
        ),
    ]
