# Generated by Django 5.0.6 on 2024-10-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_attempt_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('status',), 'permissions': [('Can_edit_status', 'Can edit status')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
