# Generated by Django 5.0.6 on 2024-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('status',), 'permissions': [('Can_is_published', 'Can is published')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Отметьте для активации', verbose_name='Опубликовано'),
        ),
    ]
